# Generated by Django 5.1.2 on 2024-10-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('height', models.CharField(max_length=5)),
                ('weight', models.CharField(max_length=10)),
                ('firstName', models.CharField(max_length=20)),
                ('mInit', models.CharField(max_length=1)),
                ('lastName', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('age', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('joinYear', models.IntegerField()),
                ('teamName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passWord', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField(default=False)),
                ('teamName', models.CharField(max_length=20)),
                ('userView', models.IntegerField(default=1)),
            ],
        ),
    ]
