# Generated by Django 5.1.2 on 2024-10-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
