# Generated by Django 5.1.2 on 2024-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_loggedin_alter_athlete_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20),
        ),
    ]
