# Generated by Django 5.1.2 on 2024-10-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_globalstats_alter_athlete_id_alter_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
