# Generated by Django 5.1.2 on 2024-10-31 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballStat',
            fields=[
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.athlete')),
                ('battingAvg', models.IntegerField(blank=True)),
                ('homeRuns', models.IntegerField(blank=True)),
                ('era', models.FloatField(blank=True)),
                ('rbi', models.IntegerField(blank=True)),
                ('stolenBases', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BasketballStat',
            fields=[
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.athlete')),
                ('pointsPG', models.IntegerField(blank=True)),
                ('assistsPG', models.IntegerField(blank=True)),
                ('reboundsPG', models.IntegerField(blank=True)),
                ('threePPerc', models.IntegerField(blank=True)),
                ('freeThrowPerc', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FootballStat',
            fields=[
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.athlete')),
                ('passingYards', models.IntegerField(blank=True)),
                ('rushingYards', models.IntegerField(blank=True)),
                ('tackles', models.IntegerField(blank=True)),
                ('sacks', models.IntegerField(blank=True)),
                ('interceptions', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerStat',
            fields=[
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.athlete')),
                ('goalsScored', models.IntegerField(blank=True)),
                ('shots', models.IntegerField(blank=True)),
                ('saves', models.IntegerField(blank=True)),
                ('fouls', models.IntegerField(blank=True)),
                ('minutesPlayed', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GlobalStats',
            new_name='GlobalStat',
        ),
        migrations.AddField(
            model_name='athlete',
            name='gamesPlayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='position',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.CharField(choices=[('Baseball', 'Baseball'), ('Basketball', 'Basketball'), ('Soccer', 'Soccer'), ('Football', 'Football')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='favAthlete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.athlete'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='firstName',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.CharField(default='N/A', max_length=5),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='lastName',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='mInit',
            field=models.CharField(default='N/A', max_length=1),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='teamName',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
