# Generated by Django 5.1.2 on 2024-10-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_baseballstat_basketballstat_footballstat_soccerstat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='joinYear',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='losses',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='wins',
            field=models.IntegerField(blank=True),
        ),
    ]
