# Generated by Django 5.1.2 on 2024-10-31 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_athlete_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favAthlete',
        ),
    ]
