# Generated by Django 5.1.2 on 2024-10-31 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_user_favathlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favAthlete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.athlete'),
        ),
    ]
