# Generated by Django 5.1.2 on 2024-10-31 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_favathlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favAthlete',
        ),
    ]
