# Generated by Django 5.1.2 on 2024-11-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_favathlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='mInit',
        ),
        migrations.AlterField(
            model_name='baseballstat',
            name='rbi',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='assistsPG',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='freeThrowPerc',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='pointsPG',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='reboundsPG',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='threePPerc',
            field=models.FloatField(blank=True),
        ),
    ]
