# Generated by Django 5.1.2 on 2024-11-10 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_athlete_minit_alter_baseballstat_rbi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
