# Generated by Django 5.1.2 on 2024-11-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_baseballstat_battingavg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='numViews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='baseballstat',
            name='homeRuns',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='baseballstat',
            name='rbi',
            field=models.IntegerField(blank=True),
        ),
    ]
