# Generated by Django 5.1.2 on 2024-11-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_athlete_gamesplayed_remove_user_userview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
