# Generated by Django 5.1.2 on 2024-11-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_athlete_losses_alter_athlete_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseballstat',
            name='battingAvg',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='baseballstat',
            name='era',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='baseballstat',
            name='homeRuns',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='baseballstat',
            name='rbi',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='baseballstat',
            name='stolenBases',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='assistsPG',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='freeThrowPerc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='pointsPG',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='reboundsPG',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='threePPerc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='interceptions',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='passingYards',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='rushingYards',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='sacks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='tackles',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='soccerstat',
            name='fouls',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='soccerstat',
            name='goalsScored',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='soccerstat',
            name='minutesPlayed',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='soccerstat',
            name='saves',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='soccerstat',
            name='shots',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
